name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_BASE: '/${{ github.event.repository.name }}/'
          ROLLUP_SKIP_NATIVE: 'true'
        run: npm run build

      - name: Debug permissions
        run: |
          echo "Actor: $GITHUB_ACTOR"
          echo "Token is available: ${GITHUB_TOKEN:+yes}"
          echo "Note: ensure Actions -> Settings -> Workflow permissions is set to 'Read and write' for this repository."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          enable_jekyll: false

      - name: Print expected Pages URL
        if: always()
        run: |
          # GITHUB_REPOSITORY is owner/repo
          owner_repo="$GITHUB_REPOSITORY"
          owner=${owner_repo%%/*}
          repo=${owner_repo##*/}
          echo "Expected GitHub Pages URL(s):"
          echo "- User/org pages (if configured): https://$owner.github.io/"
          echo "- Project pages: https://$owner.github.io/$repo/"
